# Site settings
title: Labour market tools
email:
description: > # this means to ignore newlines until "baseurl:"
  Information about URLS and websites made by the LM Tools team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lmt-information.herokuapp.com" # the base hostname & protocol for your site
twitter_username:
github_username:  lm-tools

# Build settings
markdown: kramdown
source: jekyll_source
destination: _site
